# docker-compose.yml
version: "3"
services:
  dash-app:
    build:
      context: dashboard
      dockerfile: ./Dockerfile
    image: dav/dash-app:0.0.1
    ports:
      - "8050:8050"
    environment:
      DASH_DEBUG_MODE: "True"
      SERVER_PORT: 8050