# docker-compose.yml
version: "3"
services:
  dashboard:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: openpath/opdash:0.0.1
    ports:
      - "8050:8050"
    environment:
      DASH_DEBUG_MODE: "True"
      SERVER_PORT: 8050
      DB_HOST: db
      WEB_SERVER_HOST: 0.0.0.0
      SERVER_BRANCH: master
    networks:
       - emission
    volumes:
      - ./pages:/usr/src/app/pages
      - ./app.py:/usr/src/app/app.py
      - ./app_sidebar_collapsible.py:/usr/src/app/app_sidebar_collapsible.py
  db:
    image: mongo:4.4.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - mongo-data:/data/db
    networks:
       - emission
    ports:
      - "27017:27017"

networks:
  emission:

volumes:
  mongo-data: