# docker-compose-prod-ngnix.yml
# used for testing with the ngnix reverse proxy
version: "3"
services:
  dashboard:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: e-mission/opdash:0.0.1
    environment:
      DASH_DEBUG_MODE: "True"
      DASH_SERVER_PORT: 8050
      DB_HOST: db
      WEB_SERVER_HOST: 0.0.0.0
      SERVER_BRANCH: master
      CONFIG_PATH: "https://raw.githubusercontent.com/e-mission/nrel-openpath-deploy-configs/main/configs/"
      STUDY_NAME: "stage-program"
      AUTH_TYPE: "basic" # the other option is cognito
      DASH_REQUESTS_PATHNAME_PREFIX: "/"
    networks:
       - emission
    deploy:
      restart_policy:
          condition: on-failure
    depends_on:
      - db
      - nginxrp
  db:
    image: mongo:4.4.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
       - emission
  nginxrp:
    image: nginx:1.24.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
       - emission
    volumes:
      - ./docker/ngnix.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8060:80"

  
networks:
  emission:
