# docker-compose-prod.yml
version: "3"
services:
  dashboard:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: e-mission/opdash:0.0.1
    ports:
      - "8050:8050"
    environment:
      DASH_DEBUG_MODE: "False"
      DASH_SERVER_PORT: 8050
      DB_HOST: db
      WEB_SERVER_HOST: 0.0.0.0
      SERVER_BRANCH: master
      CONFIG_PATH: "https://raw.githubusercontent.com/AlirezaRa94/nrel-openpath-deploy-configs/main/configs/"
      STUDY_NAME: "admin-dashboard-permissions"
      AUTH_TYPE: "basic" # the other option is cognito
    networks:
       - emission
    deploy:
      restart_policy:
          condition: on-failure
    depends_on:
      - db
  db:
    image: mongo:4.4.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
       - emission

networks:
  emission:
